apiVersion: capabilities.3scale.net/v1beta1
kind: Product
metadata:
  name: customer
spec:
  providerAccountRef:
    name: 3scale-admin-dev-secret
  deployment:
    apicastSelfManaged:
      stagingPublicBaseURL: "https://apis-3scale-dev-staging.apps.cluster-2q76v.2q76v.sandbox955.opentlc.com:443"
      productionPublicBaseURL: "https://apis-3scale-dev.apps.cluster-2q76v.2q76v.sandbox955.opentlc.com:443"
      authentication:
        oidc:
          issuerEndpoint: "https://zync-sso:b361ca5f-1646-4377-90dc-3f77dca10f40@sso-dev.apps.cluster-2q76v.2q76v.sandbox955.opentlc.com/auth/realms/dev"
  backendUsages:
    customer-order:
      path: /customer/order
